version: "3.9"

services:
  web:
    build: .
    container_name: articlehub_web
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&gunicorn articlehub_core.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis
    restart: always
    volumes:
      - .:/code
      - ./logs:/code/logs


  mongo:
    image: mongo:7.0
    container_name: articlehub_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"

  mongo_test:
    image: mongo:7.0
    container_name: articlehub_mongo_test
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27018:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 10s
      retries: 10

  redis:
    image: redis:7.2-alpine
    container_name: articlehub_redis
    restart: always
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: articlehub_celery
    command: sh -c "sleep 10 && celery -A articlehub_core worker -l info"
    depends_on:
      - web
      - redis
    restart: always
    volumes:
      - .:/code
      - ./logs:/code/logs

  celery-beat:
    build: .
    container_name: articlehub_celery_beat
    command: celery -A articlehub_core beat -l info
    depends_on:
      - web
      - redis
    restart: always
    volumes:
      - .:/code
      - ./logs:/code/logs

#  nginx:
#    image: nginx:1.27-alpine
#    container_name: articlehub_nginx
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#      - ./nginx/ssl:/etc/nginx/ssl
#    depends_on:
#      - web
#    restart: always

  test:
    build: .
    command: >
      sh -c "pytest"
    env_file:
      - .env.test
    depends_on:
      mongo_test:
        condition: service_healthy
    volumes:
      - .:/code
